# render.yaml (Versi Paling Minimalis)
services:
  # Web Service PHP kosong
  - type: web
    name: laporan-keuangan-app
    env: php
    plan: free
    buildCommand: "echo 'Build command akan diatur nanti'"
    startCommand: "echo 'Start command akan diatur nanti'"

# Database PostgreSQL kosong
databases:
  - name: laporan-keuangan-db
    plan: free