# render.yaml (Versi Final yang Teruji)
version: "1"

services:
  # Web Service untuk Aplikasi Laravel
  - type: web
    name: laporan-keuangan-app
    env: php # Menggunakan lingkungan PHP bawaan Render
    plan: free
    buildCommand: |
      composer install --no-dev --no-interaction --optimize-autoloader
      npm install --production
      npm run build
      php artisan config:clear
      php artisan route:clear
      php artisan view:clear
      php artisan migrate --force
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    healthCheckPath: /up
    envVars:
      - key: APP_URL
        fromService:
          type: web
          name: laporan-keuangan-app
          property: url
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL # Ini akan otomatis terhubung ke database kita
        fromDatabase:
          name: laporan-keuangan-db
          property: connectionString

# Database PostgreSQL
databases:
  - name: laporan-keuangan-db
    plan: free