# render.yaml - Versi Final yang Benar
# Perhatikan 'databases' dan 'services' berada di level paling kiri (tidak menjorok)

databases:
  - name: laporan-keuangan-db
    databaseName: laporan_keuangan_db
    user: laporan_keuangan_user
    plan: free

services:
  - type: web
    name: laporan-keuangan-app
    plan: free
    # 'runtime' dihapus agar Render deteksi otomatis dari composer.json
    buildCommand: |
      composer install --no-dev
      npm install --production
      npm run build
      php artisan config:clear
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    healthCheckPath: /up
    envVars:
      - key: APP_URL
        fromService:
          type: web
          name: laporan-keuangan-app
          property: url
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: laporan-keuangan-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: laporan-keuangan-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: laporan-keuangan-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: laporan-keuangan-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: laporan-keuangan-db
          property: password